name: pajjar
description: "A professional offline dictionary app with local storage capabilities."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Flutter packages
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_riverpod: ^2.5.1
  
  # File system and storage
  path_provider: ^2.1.4
  
  # Utilities
  uuid: ^4.5.0
  intl: ^0.19.0
  
  # Sharing functionality
  share_plus: ^10.0.2
  
  # Data handling
  csv: ^6.0.0
  
  # UI components
  flutter_slidable: ^3.1.1
  
  # Theming
  flex_color_scheme: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^5.0.0
  
  # App icon generation
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  # Optional: add different sizes for better quality
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/logo.png
  
  # Optional: Add fonts section if you want custom fonts
  # fonts:
  #   - family: YourCustomFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
  #       - asset: assets/fonts/YourFont-Bold.ttf
  #         weight: 700